import { test, expect, type Page } from '@playwright/test';
import { eq } from 'drizzle-orm';
import { db } from '../../lib/db';
import { credentials } from '../../lib/db/schema';
const origin='http://127.0.0.1:3000';
const password='Fixture-secure-pass-42';
async function post(page:Page,path:string,data:unknown,method='POST'){return page.request.fetch(path,{method,data,headers:{Origin:origin}});}
test('workspace end-to-end: accounts, providers, models, chat, coding, files and isolation',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));const email=`owner-${Date.now()}@example.test`;
  await page.goto('/login');await page.getByRole('button',{name:'회원가입',exact:true}).click();
  await page.getByLabel('이름',{exact:true}).fill('테스트 사용자');await page.getByLabel('이메일',{exact:true}).fill(email);await page.getByLabel('비밀번호',{exact:true}).fill(password);
  await page.getByRole('button',{name:'계정 만들기',exact:true}).click();await expect(page.getByRole('heading',{name:'무엇을 함께 만들어볼까요?'})).toBeVisible();
  await page.getByRole('button',{name:/첫 대화를 위해/}).click();await page.getByRole('button',{name:'Provider 추가',exact:true}).click();
  await page.getByLabel('Provider 이름',{exact:true}).fill('Fixture NIM');await page.getByLabel('Base URL',{exact:true}).fill('http://127.0.0.1:4010/v1');await page.getByLabel('API Key 입력',{exact:true}).fill('fixture-valid-key');
  await page.getByRole('button',{name:'Provider 저장',exact:true}).click();await expect(page.getByText('저장된 키: ••••••••-key')).toBeVisible();
  await page.getByRole('button',{name:'연결 테스트',exact:true}).click();await expect(page.locator('.test-result')).toContainText('모델 API 연결됨');
  await page.getByRole('button',{name:'모델 불러오기',exact:true}).click();await page.getByLabel('가져오기 fixture-chat',{exact:true}).check();await page.getByLabel('가져오기 fixture-code',{exact:true}).check();
  await page.getByRole('button',{name:'2개 모델 추가',exact:true}).click();await expect(page.getByRole('button',{name:'Fixture Chat 편집'})).toBeVisible();
  await page.getByRole('button',{name:'닫기',exact:true}).first().click();
  const boot=await(await page.request.get('/api/bootstrap')).json();const provider=boot.providers[0];const model=boot.models[0];expect(JSON.stringify(boot)).not.toContain('fixture-valid-key');expect(JSON.stringify(boot)).not.toContain('encryptedApiKey');
  const [stored] = await db().select().from(credentials).where(eq(credentials.providerId,provider.id));expect(stored.encryptedApiKey).toMatch(/^v1\./);expect(stored.encryptedApiKey).not.toContain('fixture-valid-key');
  await page.screenshot({path:'test-results/desktop-welcome.png',fullPage:true});
  await page.getByRole('button',{name:'모델 선택',exact:true}).click();await page.getByRole('button',{name:/Fixture Chat.*Fixture NIM/}).click();
  await page.getByLabel('메시지 입력',{exact:true}).fill('TypeScript 예제를 설명해 주세요');await page.getByRole('button',{name:'메시지 보내기',exact:true}).click();
  await expect(page.getByLabel('생성 중단',{exact:true})).toBeVisible();await expect(page.getByTestId('message-assistant').first()).toContainText('테스트 답변');await expect(page.getByLabel('생성 중단',{exact:true})).toHaveCount(0);
  await expect(page.getByTestId('message-assistant').first().locator('table')).toBeVisible();await expect(page.locator('body')).not.toContainText('DO_NOT_DISPLAY_RAW_REASONING');
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'코드 복사',exact:true}).first().click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('const answer');
  const url=page.url();await page.reload();await expect(page.getByTestId('message-assistant')).toContainText('테스트 답변');expect(page.url()).toBe(url);
  await page.getByRole('button',{name:'다시 생성',exact:true}).last().click();await expect(page.getByLabel('생성 중단')).toBeVisible();await expect(page.getByLabel('생성 중단')).toHaveCount(0,{timeout:20000});await expect(page.getByText('2 / 2',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'질문 수정',exact:true}).first().click();await page.getByLabel('메시지 입력').fill('수정한 질문');await page.getByRole('button',{name:'메시지 보내기',exact:true}).click();await expect(page.getByTestId('message-user')).toContainText('수정한 질문');await expect(page.getByLabel('생성 중단')).toHaveCount(0,{timeout:20000});
  const chatId=new URL(page.url()).searchParams.get('chat')!;const saved=await(await page.request.get(`/api/conversations/${chatId}`)).json();expect(saved.messages.length).toBeGreaterThanOrEqual(5);expect(saved.messages.some((m:{content:string})=>m.content==='TypeScript 예제를 설명해 주세요')).toBeTruthy();
  await page.getByRole('button',{name:'Artifact 열기',exact:true}).first().click();await expect(page.getByLabel('Artifact 코드 편집')).toHaveValue(/const answer/);await page.getByLabel('Artifact 코드 편집').fill('const answer = 43;');await page.getByRole('button',{name:'버전 저장'}).click();await expect(page.getByLabel('Artifact 버전')).toHaveValue('1');await page.getByRole('button',{name:'Artifact 닫기'}).click();
  const upload=await page.request.post('/api/files',{headers:{Origin:origin},multipart:{file:{name:'notes.md',mimeType:'text/markdown',buffer:Buffer.from('# Project notes\nUse TypeScript.')}}});expect(upload.status()).toBe(201);const file=await upload.json();
  const project=await(await post(page,'/api/projects',{name:'Test project',instructions:'Use TypeScript.'})).json();expect(project.id).toBeTruthy();expect((await post(page,`/api/conversations/${chatId}`,{isPinned:true,projectId:project.id},'PATCH')).ok()).toBeTruthy();
  const share=await(await post(page,`/api/conversations/${chatId}/share`,{})).json();const publicPage=await browser.newPage();await publicPage.goto(`${origin}/share/${share.id}`);await expect(publicPage.getByText('읽기 전용 공유 대화')).toBeVisible();expect(await publicPage.content()).not.toContain('fixture-valid-key');await publicPage.close();
  const other=await browser.newContext();const second=await other.newPage();await second.goto(`${origin}/login`);expect((await post(second,`${origin}/api/auth/register`,{email:`other-${Date.now()}@example.test`,password,name:'Other'})).status()).toBe(201);
  for(const path of [`/api/conversations/${chatId}`,`/api/files/${file.id}`,`/api/providers/${provider.id}/models`])expect((await second.request.get(origin+path)).status()).toBe(404);
  expect((await post(second,`${origin}/api/models/${model.id}`,{displayName:'hijacked'},'PATCH')).status()).toBe(404);await other.close();
  expect((await page.request.post('/api/projects',{data:{name:'CSRF'}})).status()).toBe(403);
  expect((await post(page,'/api/providers',{name:'SSRF',type:'openai-compatible',baseUrl:'https://127.0.0.1/v1',apiKey:'fixture-valid-key'})).status()).toBe(400);
  const badFile=await page.request.post('/api/files',{headers:{Origin:origin},multipart:{file:{name:'fake.png',mimeType:'image/png',buffer:Buffer.from('not an image')}}});expect(badFile.status()).toBe(400);
  await page.getByLabel('메시지 입력').fill('slow-stream');await page.getByLabel('메시지 보내기').click();await expect(page.getByLabel('생성 중단')).toBeVisible();await expect(page.getByTestId('message-assistant').last()).toContainText('안녕');await page.getByLabel('생성 중단').click();await expect(page.getByLabel('생성 중단')).toHaveCount(0);await expect(page.getByText('중단됨',{exact:true})).toBeVisible();
  expect((await post(page,'/api/settings',{...boot.settings,theme:'dark'},'PUT')).ok()).toBeTruthy();await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'test-results/desktop-dark-chat.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.reload();await expect(page.getByLabel('사이드바 열기')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/mobile-chat.png',fullPage:true});
  expect((await post(page,`/api/conversations/${chatId}`,undefined,'DELETE')).ok()).toBeTruthy();expect((await page.request.get(`/api/conversations/${chatId}`)).status()).toBe(404);expect((await post(page,`/api/providers/${provider.id}`,undefined,'DELETE')).ok()).toBeTruthy();
  expect((await post(page,'/api/auth/logout',{})).ok()).toBeTruthy();expect((await page.request.get('/api/bootstrap')).status()).toBe(401);expect((await post(page,'/api/auth/login',{email,password})).ok()).toBeTruthy();expect((await page.request.get('/api/bootstrap')).status()).toBe(200);expect(errors).toEqual([]);
});
