'use client';
import { useState, type FormEvent } from 'react';
import { ArrowRight, Asterisk, Eye, EyeOff, Loader2, ShieldCheck } from 'lucide-react';
import { apiFetch } from '@/lib/client';
export function LoginForm() {
  const [register, setRegister] = useState(false); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    try { await apiFetch(`/api/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify({ email: String(form.get('email')).trim(), password: form.get('password'), name: form.get('name') }) }); window.location.assign('/'); }
    catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }
  return <main className="auth-page"><section className="auth-story"><a className="brand" href="/login"><span className="brand-mark"><Asterisk size={28} /></span>nemo<span className="brand-label">workspace</span></a><div><span className="eyebrow">YOUR MODELS. YOUR WORKSPACE.</span><h1>생각에서 코드까지,<br />하나의 대화로.</h1><p>원하는 AI를 연결하고, 더 나은 답을 비교하고,<br />아이디어를 함께 만들어 보세요.</p><div className="auth-orbit" aria-hidden="true"><Asterisk size={164} strokeWidth={1} /></div></div><small><ShieldCheck size={15} /> API Key는 서버에서 암호화하여 보관합니다.</small></section><section className="auth-form-section"><div className="auth-form-wrap"><span className="eyebrow">NEMOTRON WORKSPACE</span><h2>{register ? '나만의 워크스페이스 만들기' : '다시 만나서 반가워요'}</h2><p className="muted">{register ? '계정을 만들고 원하는 모델을 연결하세요.' : '계정에 로그인하여 대화를 이어가세요.'}</p><form onSubmit={submit} className="form-stack">{register && <label>이름<input name="name" autoComplete="name" required maxLength={60} placeholder="어떻게 불러드릴까요?" /></label>}<label>이메일<input name="email" type="email" autoComplete="email" required placeholder="you@example.com" /></label><label>비밀번호<div className="password-field"><input name="password" type={show ? 'text' : 'password'} autoComplete={register ? 'new-password' : 'current-password'} required minLength={register ? 12 : 1} maxLength={64} placeholder={register ? '12자 이상 입력하세요' : '비밀번호를 입력하세요'} /><button type="button" aria-label={show ? '비밀번호 숨기기' : '비밀번호 보기'} onClick={() => setShow(!show)}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{error && <p className="error-text" role="alert">{error}</p>}<button className="button primary auth-submit" disabled={busy}>{busy ? <Loader2 size={18} className="spin" /> : <>{register ? '계정 만들기' : '로그인'}<ArrowRight size={18} /></>}</button></form><p className="auth-switch">{register ? '이미 계정이 있으신가요?' : '처음 방문하셨나요?'} <button onClick={() => { setRegister(!register); setError(''); }}>{register ? '로그인' : '회원가입'}</button></p><p className="fine-print">이메일·비밀번호 계정으로 시작합니다.<br />소셜 로그인과 이메일 비밀번호 복구는 아직 지원하지 않습니다.</p></div></section></main>;
}
