'use client';
import { useState } from 'react';
import { diffLines } from 'diff';
import { Check, Code2, Copy, Download, Eye, GitCompare, Maximize2, Minimize2, Pencil, Save, X } from 'lucide-react';
import type { Artifact } from '@/lib/types';
import { apiFetch, copyText, download } from '@/lib/client';
import { Markdown } from './markdown';
import { useFeedback } from '../ui/feedback';
export function ArtifactPanel({ artifact, onClose, onUpdate, onModify }: { artifact: Artifact; onClose(): void; onUpdate(artifact: Artifact): void; onModify(content: string, name: string): void }) {
  const { toast, confirm } = useFeedback(); const [version, setVersion] = useState(artifact.versions.length - 1); const [content, setContent] = useState(artifact.versions.at(-1) || ''); const [tab, setTab] = useState<'code' | 'preview' | 'diff'>('code'); const [full, setFull] = useState(false); const [saving, setSaving] = useState(false);
  const previewable = ['html','markdown','md'].includes(artifact.language); const dirty = content !== artifact.versions[version];
  async function save() { setSaving(true); try { const saved = await apiFetch<Artifact>(`/api/artifacts/${artifact.id}`, { method: 'PATCH', body: JSON.stringify({ content }) }); onUpdate(saved); setVersion(saved.versions.length - 1); toast('새 버전을 저장했습니다.'); } catch (error) { toast((error as Error).message, true); } finally { setSaving(false); } }
  const safeHTML = `<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src data:; form-action 'none'; base-uri 'none'; script-src 'none'"><meta name="viewport" content="width=device-width, initial-scale=1">${content}`;
  return <section className={`artifact-panel ${full ? 'fullscreen' : ''}`} aria-label="코드 Artifact"><header><span><Code2 size={18} /><strong>{artifact.name}</strong></span><div><button className="icon-button" aria-label="Artifact 전체 화면" onClick={() => setFull(!full)}>{full ? <Minimize2 size={17} /> : <Maximize2 size={17} />}</button><button className="icon-button" aria-label="Artifact 닫기" onClick={async () => { if (!dirty || await confirm('저장하지 않은 수정을 버리고 닫을까요?')) onClose(); }}><X size={18} /></button></div></header><div className="artifact-controls"><div className="tab-row"><button className={tab === 'code' ? 'active' : ''} onClick={() => setTab('code')}><Code2 size={15} />코드</button>{previewable && <button className={tab === 'preview' ? 'active' : ''} onClick={() => setTab('preview')}><Eye size={15} />Preview</button>}<button className={tab === 'diff' ? 'active' : ''} onClick={() => setTab('diff')}><GitCompare size={15} />Diff</button></div><select aria-label="Artifact 버전" value={version} onChange={async e => { const index = Number(e.target.value); if (dirty && !await confirm('저장하지 않은 수정을 버리고 버전을 바꿀까요?')) return; setVersion(index); setContent(artifact.versions[index]); }}>{artifact.versions.map((_,index) => <option key={index} value={index}>v{index + 1}</option>)}</select></div><div className="artifact-body">{tab === 'code' && <textarea aria-label="Artifact 코드 편집" spellCheck={false} value={content} onChange={e => setContent(e.target.value)} />}{tab === 'preview' && (artifact.language === 'html' ? <iframe title="HTML Artifact Preview" sandbox="" referrerPolicy="no-referrer" srcDoc={safeHTML} /> : <Markdown content={content} />)}{tab === 'diff' && <pre className="diff-view">{diffLines(artifact.versions[Math.max(0,version - 1)], content).map((part,index) => <span key={index} className={part.added ? 'added' : part.removed ? 'removed' : ''}>{part.value}</span>)}</pre>}</div>{tab === 'preview' && artifact.language === 'html' && <small className="artifact-notice">Sandbox Preview · 스크립트와 외부 네트워크는 실행하지 않습니다.</small>}<footer><button className="button small" onClick={() => void copyText(content).then(() => toast('코드를 복사했습니다.')).catch(() => toast('복사 권한을 확인해 주세요.',true))}><Copy size={14} />복사</button><button className="button small" onClick={() => download(artifact.name,content)}><Download size={14} />저장</button><button className="button small" onClick={() => onModify(content,artifact.name)}><Pencil size={14} />AI로 수정</button><button className="button primary small" disabled={!dirty || saving} onClick={() => void save()}>{dirty ? <Save size={14} /> : <Check size={14} />}버전 저장</button></footer></section>;
}
