'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, Asterisk, ChevronLeft, ChevronRight, Copy, Pencil, RotateCcw, ThumbsDown, ThumbsUp } from 'lucide-react';
import { activeBranch, newestDescendant } from '@/lib/branches';
import { apiFetch, copyText } from '@/lib/client';
import type { Workspace } from '@/hooks/use-workspace';
import type { Message } from '@/lib/types';
import { Markdown, type CodeSelection } from './markdown';
import { useFeedback } from '../ui/feedback';
export function Messages({ workspace: w, onArtifact, onEdit }: { workspace: Workspace; onArtifact(messageId: string, code: CodeSelection): void; onEdit(message: Message): void }) {
  const { toast } = useFeedback(); const scroll = useRef<HTMLDivElement>(null); const follow = useRef(true); const [below, setBelow] = useState(false); const [visible, setVisible] = useState(40);
  const branch = useMemo(() => activeBranch(w.messages, w.conversation?.activeLeafId || null), [w.messages, w.conversation?.activeLeafId]);
  useEffect(() => { if (follow.current && scroll.current) scroll.current.scrollTop = scroll.current.scrollHeight; }, [w.messages]);
  const bottom = () => { scroll.current?.scrollTo({ top: scroll.current.scrollHeight, behavior: 'smooth' }); follow.current = true; setBelow(false); };
  async function feedback(message: Message, value: 'up' | 'down') { const next = message.metadata.feedback === value ? null : value; try { await apiFetch(`/api/messages/${message.id}`, { method: 'PATCH', body: JSON.stringify({ feedback: next }) }); w.setMessages(old => old.map(x => x.id === message.id ? { ...x, metadata: { ...x.metadata, feedback: next } } : x)); } catch (error) { toast((error as Error).message, true); } }
  function switchVersion(message: Message, id: string) { void w.patchConversation(message.conversationId, { activeLeafId: newestDescendant(w.messages,id) }).catch(error => toast(error.message,true)); }
  return <div className="message-region"><div className="message-scroll" ref={scroll} onScroll={() => { const el = scroll.current!; follow.current = el.scrollHeight - el.scrollTop - el.clientHeight < 100; setBelow(!follow.current); }}><div className="messages">{branch.length > visible && <button className="button subtle" onClick={() => setVisible(x => x + 40)}>이전 메시지 40개 보기</button>}{branch.slice(-visible).map(message => {
    const alternatives = w.messages.filter(x => x.role === message.role && x.parentMessageId === message.parentMessageId); const index = alternatives.findIndex(x => x.id === message.id); const model = w.data?.models.find(x => x.id === message.modelId);
    return <article key={message.id} className={`message ${message.role}`} data-testid={`message-${message.role}`}>
      {message.role === 'assistant' && <div className="message-heading"><span className="assistant-mark"><Asterisk size={22} /></span><strong>{model?.displayName || 'Assistant'}</strong>{message.status === 'stopped' && <small>중단됨</small>}{message.status === 'streaming' && w.busy && <span className="stream-status" role="status">{w.status === 'thinking' ? '생각하는 중' : w.status === 'generating' ? '이미지/답변 생성 중' : '연결 중'}<i /></span>}</div>}
      <div className="message-content">{message.role === 'user' ? <div className="user-bubble">{message.content}</div> : <Markdown content={message.content} onArtifact={code => onArtifact(message.id, code)} />}{message.role === 'assistant' && message.metadata.generatedImageId && <div className="mt-3"><img className="max-w-full rounded-xl" src={`/api/files/${message.metadata.generatedImageId}`} alt="AI가 생성한 이미지" /><a className="button subtle small mt-2 inline-flex" href={`/api/files/${message.metadata.generatedImageId}`} download="generated-image.png">이미지 다운로드</a></div>}{w.attachments.filter(x => x.messageId === message.id || message.metadata.attachmentIds?.includes(x.id)).map(file => <a key={file.id} className="file-chip" href={`/api/files/${file.id}`} target="_blank" rel="noreferrer">{file.name} ↗</a>)}{message.status === 'error' && <p className="error-text" role="alert">{message.metadata.error || '응답을 완료하지 못했습니다. 다시 생성해 주세요.'}</p>}{message.status === 'streaming' && !w.busy && <p className="muted">이전 생성이 중단되었을 수 있습니다. 다시 생성할 수 있습니다.</p>}</div>
      <div className="message-actions"><button aria-label="메시지 복사" onClick={() => void copyText(message.content).then(() => toast('복사했습니다.')).catch(() => toast('복사 권한을 확인해 주세요.', true))}><Copy size={15} /></button>{message.role === 'user' ? <button aria-label="질문 수정" disabled={w.busy} onClick={() => onEdit(message)}><Pencil size={15} /></button> : <><button aria-label="좋아요" aria-pressed={message.metadata.feedback === 'up'} onClick={() => void feedback(message, 'up')}><ThumbsUp size={15} /></button><button aria-label="싫어요" aria-pressed={message.metadata.feedback === 'down'} onClick={() => void feedback(message, 'down')}><ThumbsDown size={15} /></button><button aria-label="다시 생성" title="현재 선택한 모델로 다시 생성" disabled={w.busy} onClick={() => void w.send({ regenerateId: message.id })}><RotateCcw size={15} /></button><select aria-label="다른 모델로 다시 생성" value="" disabled={w.busy} onChange={e => { if (e.target.value) void w.send({ regenerateId: message.id, selectedModelId: e.target.value }); }}><option value="">다른 모델로</option>{w.data?.models.filter(x => x.isEnabled).map(x => <option key={x.id} value={x.id}>{x.displayName}</option>)}</select></>}{alternatives.length > 1 && <span className="version-control"><button aria-label="이전 버전" disabled={index === 0 || w.busy} onClick={() => switchVersion(message,alternatives[index - 1].id)}><ChevronLeft size={14} /></button>{index + 1} / {alternatives.length}<button aria-label="다음 버전" disabled={index === alternatives.length - 1 || w.busy} onClick={() => switchVersion(message,alternatives[index + 1].id)}><ChevronRight size={14} /></button></span>}{message.metadata.totalTokens != null && <small>{message.metadata.totalTokens.toLocaleString()} tokens</small>}</div>
    </article>;
  })}</div></div>{below && <button className="jump-bottom icon-button" aria-label="최신 메시지로 이동" onClick={bottom}><ArrowDown size={18} /></button>}</div>;
}
