'use client';
import { useState } from 'react';
import { Check, ChevronDown, Cpu, Search, Star, SlidersHorizontal } from 'lucide-react';
import type { AIModel, Capability, GenerationOptions, ModelOption, Provider } from '@/lib/types';
import { Dialog } from '../ui/dialog';
export function ModelSelector({ models, providers, value, onChange, onFavorite, onSettings, disabled = false }: { models: AIModel[]; providers: Provider[]; value: string; onChange(id: string): void; onFavorite(model: AIModel): void; onSettings(): void; disabled?: boolean }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [provider, setProvider] = useState(''); const [capability, setCapability] = useState('');
  const selected = models.find(x => x.id === value);
  const visible = models.filter(x => x.isEnabled && providers.some(p => p.id === x.providerId && p.isEnabled) && (!provider || x.providerId === provider) && (!capability || x.capabilities.includes(capability as Capability)) && `${x.displayName} ${x.modelId}`.toLowerCase().includes(query.toLowerCase()));
  const favorites = visible.filter(x => x.isFavorite); const recent = visible.filter(x => !x.isFavorite && x.lastUsedAt).sort((a,b) => (b.lastUsedAt || '').localeCompare(a.lastUsedAt || '')).slice(0,3); const rest = visible.filter(x => !favorites.includes(x) && !recent.includes(x));
  return <><button className="model-trigger" disabled={disabled} onClick={() => setOpen(true)} aria-label="모델 선택"><span className="model-dot" />{selected?.displayName || '모델 선택'}<ChevronDown size={15} /></button><Dialog open={open} onClose={() => setOpen(false)} title="모델 선택" className="model-dialog"><div className="dialog-body"><div className="search-input"><Search size={18} /><input autoFocus aria-label="모델 검색" placeholder="모델 이름 또는 ID 검색" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="filter-row"><select aria-label="Provider 필터" value={provider} onChange={e => setProvider(e.target.value)}><option value="">모든 Provider</option>{providers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="기능 필터" value={capability} onChange={e => setCapability(e.target.value)}><option value="">모든 기능</option>{['vision','code','reasoning','tools'].map(x => <option key={x}>{x}</option>)}</select></div>{!visible.length && <div className="empty-state"><Cpu size={32} /><p>사용 가능한 모델이 없습니다.</p><button className="button primary" onClick={() => { setOpen(false); onSettings(); }}>Provider / 모델 추가</button></div>}{([['즐겨찾기', favorites], ['최근 사용', recent], ['모든 모델', rest]] as [string, AIModel[]][]).map(([title, group]) => group.length > 0 && <section key={title} className="model-group"><h3>{title}</h3>{group.map(model => <div key={model.id} className={`model-option ${model.id === value ? 'selected' : ''}`}><button onClick={() => { onChange(model.id); setOpen(false); }}><span className="provider-avatar"><Cpu size={18} /></span><span><strong>{model.displayName}</strong><small>{providers.find(p => p.id === model.providerId)?.name} · {model.capabilities.join(' · ')}</small></span>{model.id === value && <Check size={17} />}</button><button className="icon-button" aria-label={`${model.displayName} 즐겨찾기`} aria-pressed={model.isFavorite} onClick={() => onFavorite(model)}><Star size={17} fill={model.isFavorite ? 'currentColor' : 'none'} /></button></div>)}</section>)}<button className="button subtle full-width" onClick={() => { setOpen(false); onSettings(); }}><SlidersHorizontal size={16} />모델 및 Provider 관리</button></div></Dialog></>;
}
const numerical: { key: ModelOption & keyof GenerationOptions; name: string; min: number; max: number; step: number }[] = [
  { key: 'temperature', name: 'Temperature', min: 0, max: 2, step: .1 }, { key: 'topP', name: 'Top P', min: 0, max: 1, step: .05 }, { key: 'maxTokens', name: 'Max output tokens', min: 1, max: 131072, step: 1 }, { key: 'frequencyPenalty', name: 'Frequency penalty', min: -2, max: 2, step: .1 }, { key: 'presencePenalty', name: 'Presence penalty', min: -2, max: 2, step: .1 },
];
export function AdvancedSettings({ open, onClose, model, options, setOptions, systemPrompt, setSystemPrompt, onSave }: { open: boolean; onClose(): void; model?: AIModel; options: GenerationOptions; setOptions(value: GenerationOptions): void; systemPrompt: string; setSystemPrompt(value: string): void; onSave(): void }) {
  return <Dialog open={open} onClose={onClose} title="대화 고급 설정"><div className="dialog-body form-stack"><p className="muted">현재 모델: {model?.displayName || '미선택'} · 지원하도록 등록한 옵션만 전송합니다.</p>{numerical.filter(x => model?.supportedOptions.includes(x.key)).map(field => <label key={field.key}>{field.name}<input type="number" min={field.min} max={field.key === 'maxTokens' ? model?.maxOutputTokens : field.max} step={field.step} value={options[field.key] ?? ''} onChange={e => setOptions({ ...options, [field.key]: e.target.value === '' ? undefined : Number(e.target.value) })} /></label>)}{model?.capabilities.includes('reasoning') && ['nvidia','effort'].includes(model.reasoningStyle) && <label>Reasoning effort<select value={options.reasoningEffort || 'off'} onChange={e => setOptions({ ...options, reasoningEffort: e.target.value as GenerationOptions['reasoningEffort'] })}>{['off','low','medium','high'].map(x => <option key={x}>{x}</option>)}</select></label>}<label>대화 System Prompt<textarea rows={5} maxLength={16000} value={systemPrompt} onChange={e => setSystemPrompt(e.target.value)} placeholder="이 대화에서 사용할 추가 지침" /></label><p className="fine-print">개인 지침 → 메모리 → 프로젝트 → 대화 지침 순서로 합칩니다. 충돌 시 대화 지침을 우선합니다.</p><button className="button primary" onClick={onSave}>적용</button></div></Dialog>;
}
