'use client';
import { useState, type FormEvent } from 'react';
import { Cpu, Download, Pencil, Plus, Trash2, X } from 'lucide-react';
import type { AIModel, Bootstrap, Capability, ModelOption } from '@/lib/types';
import { apiFetch } from '@/lib/client';
import { nemotronPreset } from '@/lib/ai/presets';
import { useFeedback } from '../ui/feedback';
type ModelForm = Omit<AIModel, 'id' | 'lastUsedAt'>;
const empty: ModelForm = { providerId: '', modelId: '', displayName: '', description: '', contextWindow: 32768, maxOutputTokens: 4096, capabilities: ['text','code'], supportedOptions: ['temperature','topP','maxTokens'], outputTokenParam: 'max_tokens', reasoningStyle: 'none', isEnabled: true, isFavorite: false };
export function ModelsPanel({ data, reload, providerId }: { data: Bootstrap; reload(): Promise<unknown>; providerId?: string }) {
  const { toast, confirm } = useFeedback(); const [form, setForm] = useState<ModelForm | null>(null); const [editId, setEditId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [discovered, setDiscovered] = useState<{ id: string; name: string }[] | null>(null); const [checked, setChecked] = useState<string[]>([]); const [discoveryProvider, setDiscoveryProvider] = useState(providerId || data.providers[0]?.id || ''); const [search, setSearch] = useState('');
  const models = data.models.filter(x => !providerId || x.providerId === providerId);
  async function save(event: FormEvent) { event.preventDefault(); if (!form) return; setBusy(true); try { await apiFetch(editId ? `/api/models/${editId}` : '/api/models', { method: editId ? 'PATCH' : 'POST', body: JSON.stringify(form) }); setForm(null); await reload(); toast('모델을 저장했습니다.'); } catch (error) { toast((error as Error).message, true); } finally { setBusy(false); } }
  async function discover() { if (!discoveryProvider) return; setBusy(true); try { setDiscovered(await apiFetch(`/api/providers/${discoveryProvider}/models`)); setChecked([]); } catch (error) { toast((error as Error).message + ' 수동으로도 모델을 등록할 수 있습니다.', true); } finally { setBusy(false); } }
  async function importModels() { setBusy(true); try { await apiFetch(`/api/providers/${discoveryProvider}/models/import`, { method: 'POST', body: JSON.stringify({ models: discovered?.filter(x => checked.includes(x.id)).map(x => ({ modelId: x.id, displayName: x.name.slice(0,120) })) }) }); setDiscovered(null); await reload(); toast('모델을 추가했습니다. 기능과 컨텍스트 한도를 확인해 주세요.'); } catch (error) { toast((error as Error).message, true); } finally { setBusy(false); } }
  const toggle = <T extends string,>(list: T[], value: T) => list.includes(value) ? list.filter(x => x !== value) : [...list, value];
  return <section className="settings-section"><div className="section-heading"><div><h3>Models</h3><p>모델과 지원 기능을 직접 관리하세요.</p></div><button className="button primary" disabled={!data.providers.length} onClick={() => { setEditId(null); setForm({ ...empty, providerId: providerId || data.providers[0]?.id || '' }); }}><Plus size={16} />모델 추가</button></div><div className="inline-controls">{!providerId && <select aria-label="모델 불러올 Provider" value={discoveryProvider} onChange={e => setDiscoveryProvider(e.target.value)}><option value="">Provider 선택</option>{data.providers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select>}<button className="button" disabled={busy || !discoveryProvider} onClick={() => void discover()}><Download size={16} />{busy ? '처리 중…' : '모델 불러오기'}</button></div>{!models.length && !form && <div className="empty-state"><Cpu size={30} /><p>아직 모델이 없습니다.</p><small>Provider에서 불러오거나 Model ID를 직접 입력하세요.</small></div>}
    {models.map(model => <div className="settings-list-row" key={model.id}><Cpu size={20} /><div className="grow"><strong>{model.displayName}</strong><small>{model.modelId}</small><small>{model.capabilities.join(' · ')}{!model.isEnabled && ' · 비활성'}</small></div><button className="icon-button" aria-label={`${model.displayName} 편집`} onClick={() => { setEditId(model.id); setForm(model); }}><Pencil size={16} /></button><button className="icon-button" aria-label={`${model.displayName} 삭제`} onClick={async () => { if (await confirm('모델 등록을 삭제할까요? 기존 대화 내용은 유지됩니다.')) try { await apiFetch(`/api/models/${model.id}`, { method: 'DELETE' }); await reload(); } catch (error) { toast((error as Error).message, true); } }}><Trash2 size={16} /></button></div>)}
    {discovered && <div className="sub-panel"><div className="section-heading"><h3>발견한 모델 {discovered.length}개</h3><button className="icon-button" aria-label="모델 불러오기 닫기" onClick={() => setDiscovered(null)}><X size={18} /></button></div><input aria-label="발견한 모델 검색" placeholder="모델 검색" value={search} onChange={e => setSearch(e.target.value)} /><div className="discovery-list">{discovered.filter(x => `${x.id} ${x.name}`.toLowerCase().includes(search.toLowerCase())).map(model => <label className="check-row" key={model.id}><input aria-label={`가져오기 ${model.id}`} type="checkbox" disabled={!checked.includes(model.id) && checked.length >= 100} checked={checked.includes(model.id)} onChange={() => setChecked(toggle(checked, model.id))} /><span>{model.name}<small>{model.id}</small></span></label>)}</div><button className="button primary" disabled={busy || !checked.length} onClick={() => void importModels()}>{checked.length}개 모델 추가</button></div>}
    {form && <form onSubmit={save} className="sub-panel form-stack"><div className="section-heading"><h3>{editId ? '모델 편집' : '모델 추가'}</h3><button type="button" className="icon-button" aria-label="모델 편집 취소" onClick={() => setForm(null)}><X size={18} /></button></div><label>Provider<select required disabled={!!editId} value={form.providerId} onChange={e => setForm({ ...form, providerId: e.target.value })}>{data.providers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{!editId && <button className="button subtle" type="button" onClick={() => setForm({ ...form, ...nemotronPreset, capabilities: ['text','code','reasoning'], reasoningStyle: 'nvidia', supportedOptions: ['temperature','topP','maxTokens','reasoningEffort'], maxOutputTokens: 16384 })}>NVIDIA Nemotron 예제 채우기</button>}
      <label>Model ID<input required value={form.modelId} onChange={e => setForm({ ...form, modelId: e.target.value })} placeholder="nvidia/nemotron-3-ultra-550b-a55b" /></label><label>Display Name<input required maxLength={120} value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} /></label><label>설명<input maxLength={2000} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><div className="form-grid"><label>Context window<input type="number" min={1024} max={2000000} required value={form.contextWindow} onChange={e => setForm({ ...form, contextWindow: Number(e.target.value) })} /></label><label>Max output tokens<input type="number" min={1} max={131072} required value={form.maxOutputTokens} onChange={e => setForm({ ...form, maxOutputTokens: Number(e.target.value) })} /></label></div>
      <fieldset><legend>Capabilities</legend><div className="checkbox-grid">{(['text','vision','code','tools','reasoning','image','audio'] as Capability[]).map(value => <label className="check-row" key={value}><input type="checkbox" checked={form.capabilities.includes(value)} onChange={() => setForm({ ...form, capabilities: toggle(form.capabilities, value) })} />{value}</label>)}</div><small>Image·Audio 생성과 Tool 실행은 메타데이터만 지원합니다.</small></fieldset><fieldset><legend>지원 요청 옵션</legend><div className="checkbox-grid">{(['temperature','topP','maxTokens','frequencyPenalty','presencePenalty','reasoningEffort'] as ModelOption[]).map(value => <label className="check-row" key={value}><input type="checkbox" checked={form.supportedOptions.includes(value)} onChange={() => setForm({ ...form, supportedOptions: toggle(form.supportedOptions, value) })} />{value}</label>)}</div></fieldset>
      <div className="form-grid"><label>Output token parameter<select value={form.outputTokenParam} onChange={e => setForm({ ...form, outputTokenParam: e.target.value as AIModel['outputTokenParam'] })}><option>max_tokens</option><option>max_completion_tokens</option></select></label><label>Reasoning API<select value={form.reasoningStyle} onChange={e => setForm({ ...form, reasoningStyle: e.target.value as AIModel['reasoningStyle'] })}><option value="none">추가 옵션 없음</option><option value="nvidia">NVIDIA enable_thinking</option><option value="effort">OpenAI reasoning_effort</option></select></label></div><label className="check-row"><input type="checkbox" checked={form.isEnabled} onChange={e => setForm({ ...form, isEnabled: e.target.checked })} />사용</label><button className="button primary" disabled={busy}>모델 저장</button>
    </form>}
  </section>;
}
