'use client';
import { useState, type FormEvent } from 'react';
import { Monitor, Moon, Sun, Trash2 } from 'lucide-react';
import type { Workspace } from '@/hooks/use-workspace';
import type { Settings } from '@/lib/types';
import { apiFetch } from '@/lib/client';
import { useFeedback } from '../ui/feedback';
export function PreferencesPanel({ workspace: w, section }: { workspace: Workspace; section: 'general' | 'appearance' | 'personalization' }) {
  const { toast } = useFeedback(); const [settings, setSettings] = useState(w.data!.settings); const [saving, setSaving] = useState(false); const [memory, setMemory] = useState('');
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); try { await apiFetch('/api/settings', { method: 'PUT', body: JSON.stringify(settings) }); await w.loadData(); w.setOptions(settings.options); toast('설정을 저장했습니다.'); } catch (error) { toast((error as Error).message, true); } finally { setSaving(false); } }
  return <section className="settings-section"><h3>{section === 'general' ? 'General' : section === 'appearance' ? 'Appearance' : 'Personalization'}</h3><form className="form-stack" onSubmit={save}>
    {section === 'general' && <><label>Language<select value={settings.language} onChange={e => setSettings({ ...settings, language: e.target.value as Settings['language'] })}><option value="ko">한국어</option><option value="en">English (주요 채팅 UI)</option></select></label><label>기본 모델<select value={settings.defaultModelId || ''} onChange={e => setSettings({ ...settings, defaultModelId: e.target.value || null })}><option value="">첫 번째 사용 가능한 모델</option>{w.data?.models.map(model => <option key={model.id} value={model.id}>{model.displayName}</option>)}</select></label><label>기본 프로젝트<select value={settings.defaultProjectId || ''} onChange={e => setSettings({ ...settings, defaultProjectId: e.target.value || null })}><option value="">프로젝트 없음</option>{w.data?.projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={settings.enterToSend} onChange={e => setSettings({ ...settings, enterToSend: e.target.checked })} />Enter로 전송 (Shift + Enter 줄바꿈)</label></>}
    {section === 'appearance' && <><label>Theme</label><div className="theme-options">{([['system',Monitor,'시스템'],['light',Sun,'라이트'],['dark',Moon,'다크']] as const).map(([value,Icon,label]) => <button type="button" className={settings.theme === value ? 'selected' : ''} aria-pressed={settings.theme === value} key={value} onClick={() => setSettings({ ...settings, theme: value })}><Icon size={24} />{label}</button>)}</div><label>글자 크기 · {settings.fontSize}px<input type="range" min={13} max={20} value={settings.fontSize} onChange={e => setSettings({ ...settings, fontSize: Number(e.target.value) })} /></label><label>코드 테마<select value={settings.codeTheme} onChange={e => setSettings({ ...settings, codeTheme: e.target.value as Settings['codeTheme'] })}><option value="dark">Dark</option><option value="light">Light</option></select></label><label className="check-row"><input type="checkbox" checked={settings.compact} onChange={e => setSettings({ ...settings, compact: e.target.checked })} />간격을 좁게 표시</label></>}
    {section === 'personalization' && <><label>AI가 나에 대해 알아야 할 내용<textarea rows={4} maxLength={8000} value={settings.aboutYou} onChange={e => setSettings({ ...settings, aboutYou: e.target.value })} placeholder="사용 언어, 선호하는 기술, 작업 배경…" /></label><label>AI가 어떻게 답변하면 좋을까요?<textarea rows={4} maxLength={8000} value={settings.responseStyle} onChange={e => setSettings({ ...settings, responseStyle: e.target.value })} placeholder="간결하게 답변하고 코드는 TypeScript로 작성해 주세요." /></label><p className="fine-print">개인 지침 → 메모리 → 프로젝트 → 대화 지침 순서로 적용합니다. 다음 요청부터 사용됩니다.</p><label className="check-row"><input type="checkbox" checked={settings.memoryEnabled} onChange={e => setSettings({ ...settings, memoryEnabled: e.target.checked })} />수동 메모리 사용</label></>}
    <button className="button primary" disabled={saving}>{saving ? '저장 중…' : '설정 저장'}</button></form>
    {section === 'personalization' && <div className="sub-panel"><h3>Memory</h3><p className="muted">직접 추가한 메모리만 사용합니다. 자동 추출하지 않습니다.</p>{w.data?.memories.map(item => <div className="settings-list-row" key={item.id}><label className="check-row grow"><input type="checkbox" checked={item.enabled} onChange={async e => { try { await apiFetch(`/api/memories/${item.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: e.target.checked }) }); await w.loadData(); } catch (error) { toast((error as Error).message, true); } }} />{item.content}</label><button className="icon-button" aria-label="메모리 삭제" onClick={async () => { try { await apiFetch(`/api/memories/${item.id}`, { method: 'DELETE' }); await w.loadData(); } catch (error) { toast((error as Error).message, true); } }}><Trash2 size={16} /></button></div>)}<form className="inline-controls" onSubmit={async e => { e.preventDefault(); try { await apiFetch('/api/memories', { method: 'POST', body: JSON.stringify({ content: memory }) }); setMemory(''); await w.loadData(); } catch (error) { toast((error as Error).message, true); } }}><input aria-label="새 메모리" value={memory} onChange={e => setMemory(e.target.value)} required maxLength={2000} placeholder="예: 코드는 TypeScript를 선호함" /><button className="button">추가</button></form></div>}
  </section>;
}
