'use client';
import { useState, type FormEvent } from 'react';
import { ChevronLeft, Eye, EyeOff, KeyRound, Plus, Plug, ShieldCheck, Trash2 } from 'lucide-react';
import type { Bootstrap, Provider } from '@/lib/types';
import { providerPresets } from '@/lib/ai/presets';
import { apiFetch } from '@/lib/client';
import { useFeedback } from '../ui/feedback';
import { ModelsPanel } from './models-panel';
type ProviderForm = Omit<Provider, 'id' | 'keyHint'> & { apiKey: string };
const initial: ProviderForm = { ...providerPresets[0], icon: null, isEnabled: true, apiKey: '' };
export function ProvidersPanel({ data, reload }: { data: Bootstrap; reload(): Promise<unknown> }) {
  const { toast, confirm } = useFeedback(); const [selected, setSelected] = useState<string | null>(null); const [form, setForm] = useState<ProviderForm | null>(null); const [showKey, setShowKey] = useState(false); const [busy, setBusy] = useState(false); const [testResult, setTestResult] = useState(''); const provider = data.providers.find(x => x.id === selected);
  async function save(event: FormEvent) { event.preventDefault(); if (!form) return; setBusy(true); try { const saved = await apiFetch<Provider>(selected ? `/api/providers/${selected}` : '/api/providers', { method: selected ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, apiKey: form.apiKey || undefined }) }); setForm({ ...saved, apiKey: '' }); setShowKey(false); setSelected(saved.id); await reload(); toast('Provider를 저장했습니다. API Key는 암호화하여 보관합니다.'); } catch (error) { toast((error as Error).message, true); } finally { setBusy(false); } }
  async function test() { if (!selected) return; setBusy(true); setTestResult('연결 확인 중…'); try { setTestResult((await apiFetch<{ message: string }>(`/api/providers/${selected}/test`, { method: 'POST', body: '{}' })).message); } catch (error) { setTestResult((error as Error).message); } finally { setBusy(false); } }
  if (form) return <section className="settings-section"><button className="back-link" onClick={() => { setForm(null); setSelected(null); setTestResult(''); }}><ChevronLeft size={16} />AI Providers</button><h3>{selected ? `${provider?.name || form.name} 설정` : 'Provider 추가'}</h3><form className="form-stack" onSubmit={save}>
    <label>Provider Preset<select aria-label="Provider Preset" defaultValue="" onChange={e => { const preset = providerPresets[Number(e.target.value)]; if (preset) setForm({ ...form, ...preset }); }}><option value="" disabled>Preset 선택</option>{providerPresets.map((preset, index) => <option value={index} key={preset.name}>{preset.name}</option>)}</select></label><div className="form-grid"><label>Provider 이름<input required maxLength={120} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Provider Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value as Provider['type'] })}><option value="openai-compatible">OpenAI Compatible</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option></select></label></div><label>Base URL<input type="url" required value={form.baseUrl} onChange={e => setForm({ ...form, baseUrl: e.target.value })} placeholder="https://integrate.api.nvidia.com/v1" /></label><p className="fine-print">Custom 호스트는 서버의 AI_ALLOWED_HOSTS에 등록해야 합니다.</p>
    <label>API Key {provider && <small>저장된 키: {provider.keyHint}</small>}<div className="password-field"><input aria-label="API Key 입력" type={showKey ? 'text' : 'password'} autoComplete="off" spellCheck={false} required={!selected} value={form.apiKey} onChange={e => setForm({ ...form, apiKey: e.target.value })} placeholder={selected ? '변경할 때만 새 Key 입력' : 'API Key를 입력하세요'} /><button type="button" aria-label={showKey ? 'API Key 숨기기' : 'API Key 보기'} onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>
    <details className="advanced-details"><summary>Endpoint 및 고급 옵션</summary><div className="form-grid"><label>Chat Endpoint<input value={form.chatEndpoint} onChange={e => setForm({ ...form, chatEndpoint: e.target.value })} required /></label><label>Models Endpoint<input value={form.modelsEndpoint} onChange={e => setForm({ ...form, modelsEndpoint: e.target.value })} required /></label></div><label>아이콘 (문자 또는 이모지)<input maxLength={8} value={form.icon || ''} onChange={e => setForm({ ...form, icon: e.target.value })} /></label><label className="check-row"><input type="checkbox" checked={form.isEnabled} onChange={e => setForm({ ...form, isEnabled: e.target.checked })} />Provider 사용</label></details><div className="form-actions"><button className="button primary" disabled={busy}>{busy ? '처리 중…' : 'Provider 저장'}</button>{selected && <button type="button" className="button" disabled={busy || !!form.apiKey} onClick={() => void test()}><Plug size={16} />연결 테스트</button>}</div>{testResult && <p className="test-result" role="status">{testResult}</p>}<p className="fine-print"><ShieldCheck size={14} />전체 Key는 다시 조회할 수 없습니다. 연결 테스트는 소량의 토큰을 사용할 수 있습니다.</p>
    </form>{selected && <ModelsPanel key={selected} data={data} reload={reload} providerId={selected} />}</section>;
  return <section className="settings-section"><div className="section-heading"><div><h3>AI Providers</h3><p>내 API Key로 원하는 AI를 연결하세요.</p></div><button className="button primary" onClick={() => { setSelected(null); setForm(initial); }}><Plus size={16} />Provider 추가</button></div>{!data.providers.length && <div className="empty-state"><span className="empty-icon"><KeyRound size={30} /></span><h4>첫 번째 AI를 연결해 보세요</h4><p>NVIDIA NIM부터 Custom API까지.<br />키는 브라우저에 저장하지 않습니다.</p><button className="button" onClick={() => setForm(initial)}>NVIDIA NIM 연결</button></div>}{data.providers.map(item => <div className="settings-list-row" key={item.id}><span className="provider-avatar">{item.icon || <Plug size={19} />}</span><button className="grow text-left" onClick={() => { setSelected(item.id); setForm({ ...item, apiKey: '' }); }}><strong>{item.name} {!item.isEnabled && '(비활성)'}</strong><small>{item.baseUrl}</small><small>{item.keyHint} · {data.models.filter(x => x.providerId === item.id).length} models</small></button><button className="button small" onClick={() => { setSelected(item.id); setForm({ ...item, apiKey: '' }); }}>관리</button><button className="icon-button" aria-label={`${item.name} Provider 삭제`} onClick={async () => { if (await confirm(`${item.name} Provider와 암호화 Key, 등록 모델을 삭제할까요? 대화 내용은 유지됩니다.`)) try { await apiFetch(`/api/providers/${item.id}`, { method: 'DELETE' }); await reload(); } catch (error) { toast((error as Error).message, true); } }}><Trash2 size={17} /></button></div>)}<div className="security-note"><ShieldCheck size={20} /><p>API Key는 AES-256-GCM으로 암호화합니다. 모든 AI 요청은 서버 Proxy를 거칩니다.</p></div></section>;
}
