'use client';
import { useState } from 'react';
import { LogOut, ShieldCheck, Trash2 } from 'lucide-react';
import { apiFetch } from '@/lib/client';
import { useFeedback } from '../ui/feedback';
export function SecurityPanel() {
  const { toast, confirm } = useFeedback(); const [busy, setBusy] = useState(false); const [deleting, setDeleting] = useState(false);
  return <section className="settings-section"><h3>Security</h3><div className="security-note"><ShieldCheck size={21} /><p>비밀번호를 변경하면 다른 세션의 로그인이 해제됩니다.</p></div><form className="form-stack" onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); setBusy(true); try { await apiFetch('/api/auth/password', { method: 'POST', body: JSON.stringify({ currentPassword: values.get('current'), newPassword: values.get('next') }) }); form.reset(); toast('비밀번호를 변경했습니다.'); } catch (error) { toast((error as Error).message, true); } finally { setBusy(false); } }}><label>현재 비밀번호<input name="current" type="password" required autoComplete="current-password" /></label><label>새 비밀번호<input name="next" type="password" required minLength={12} maxLength={64} autoComplete="new-password" /></label><button className="button primary" disabled={busy}>비밀번호 변경</button></form><hr /><button className="button" onClick={async () => { try { await apiFetch('/api/auth/logout', { method: 'POST', body: '{}' }); window.location.assign('/login'); } catch (error) { toast((error as Error).message, true); } }}><LogOut size={16} />로그아웃</button><hr /><h3>계정 삭제</h3><p className="muted">대화, 파일, API Key, 프로젝트와 공유 링크가 영구 삭제됩니다.</p><button className="button danger" onClick={() => setDeleting(!deleting)}><Trash2 size={16} />계정 삭제 절차</button>{deleting && <form className="form-stack sub-panel" onSubmit={async event => { event.preventDefault(); const password = new FormData(event.currentTarget).get('password'); if (!await confirm('계정과 모든 데이터를 영구 삭제할까요? 이 작업은 취소할 수 없습니다.')) return; setBusy(true); try { await apiFetch('/api/auth/account', { method: 'DELETE', body: JSON.stringify({ password, confirmation: 'DELETE' }) }); window.location.assign('/login'); } catch (error) { toast((error as Error).message, true); } finally { setBusy(false); } }}><label>본인 확인용 비밀번호<input type="password" name="password" required autoComplete="current-password" /></label><button className="button danger" disabled={busy}>계정 영구 삭제</button></form>}</section>;
}
