'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { File, Plus, Trash2 } from 'lucide-react';
import type { Attachment, Conversation, Project } from '@/lib/types';
import type { Workspace } from '@/hooks/use-workspace';
import { apiFetch } from '@/lib/client';
import { Dialog } from '../ui/dialog';
import { useFeedback } from '../ui/feedback';
export function ProjectDialog({ workspace: w, projectId, onClose }: { workspace: Workspace; projectId: string | null; onClose(): void }) {
  const { toast, confirm } = useFeedback(); const original = w.data?.projects.find(x => x.id === projectId); const [project, setProject] = useState(original); const [name, setName] = useState(original?.name || ''); const [description, setDescription] = useState(original?.description || ''); const [instructions, setInstructions] = useState(original?.instructions || ''); const [tab, setTab] = useState('instructions'); const [files, setFiles] = useState<Attachment[]>([]); const [chats, setChats] = useState<Conversation[]>([]); const [busy, setBusy] = useState(false); const [chatMore, setChatMore] = useState(false); const upload = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!project?.id) return; Promise.all([apiFetch<Attachment[]>(`/api/files?projectId=${project.id}`), apiFetch<{ items: Conversation[]; hasMore: boolean }>(`/api/conversations?projectId=${project.id}`)]).then(([f,c]) => { setFiles(f); setChats(c.items); setChatMore(c.hasMore); }).catch(error => toast(error.message, true)); }, [project?.id, toast]);
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); try { const row = await apiFetch<Project>(project ? `/api/projects/${project.id}` : '/api/projects', { method: project ? 'PATCH' : 'POST', body: JSON.stringify({ name, description, instructions }) }); setProject(row); await w.loadData(); toast('프로젝트를 저장했습니다.'); } catch (error) { toast((error as Error).message, true); } finally { setBusy(false); } }
  return <Dialog open onClose={onClose} title={project ? project.name : '새 프로젝트'} className="project-dialog"><div className="dialog-body"><div className="tab-row">{[['instructions','지침'],['files','파일'],['chats','대화']].map(([value,label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)} disabled={!project && value !== 'instructions'}>{label}</button>)}</div>{tab === 'instructions' && <form className="form-stack" onSubmit={save}><label>프로젝트 이름<input required maxLength={120} value={name} onChange={e => setName(e.target.value)} placeholder="예: Python Backend" /></label><label>설명<input maxLength={2000} value={description} onChange={e => setDescription(e.target.value)} /></label><label>프로젝트 지침<textarea rows={7} maxLength={16000} value={instructions} onChange={e => setInstructions(e.target.value)} placeholder="모든 코드는 Python 3.13 기준으로 작성하고 FastAPI를 우선 사용해 주세요." /></label><p className="fine-print">프로젝트에 속한 모든 대화의 다음 AI 요청에 적용됩니다.</p><div className="form-actions"><button className="button primary" disabled={busy}>프로젝트 저장</button>{project && <button type="button" className="button danger" onClick={async () => { if (!await confirm('프로젝트와 프로젝트 파일을 삭제할까요? 대화는 일반 대화로 남습니다.')) return; try { await apiFetch(`/api/projects/${project.id}`, { method: 'DELETE' }); await w.loadData(); if (w.projectId === project.id) w.newChat(); onClose(); } catch (error) { toast((error as Error).message, true); } }}><Trash2 size={16} />삭제</button>}</div></form>}
    {tab === 'files' && <><div className="section-heading"><p className="muted">대화에서 + → 프로젝트 파일 선택으로 첨부합니다.</p><button className="button" disabled={busy} onClick={() => upload.current?.click()}><Plus size={16} />파일 추가</button></div>{files.map(file => <div className="settings-list-row" key={file.id}><File size={18} /><a className="grow" href={`/api/files/${file.id}`}>{file.name}</a><button className="icon-button" aria-label={`${file.name} 삭제`} onClick={async () => { if (await confirm('프로젝트 파일을 삭제할까요? 이후 요청의 컨텍스트에서 제외됩니다.')) try { await apiFetch(`/api/files/${file.id}`, { method: 'DELETE' }); setFiles(old => old.filter(x => x.id !== file.id)); } catch (error) { toast((error as Error).message, true); } }}><Trash2 size={16} /></button></div>)}{!files.length && <div className="empty-state">README, API 문서, 소스 코드를 추가해 보세요.</div>}<input type="file" ref={upload} hidden onChange={async e => { const file = e.target.files?.[0]; if (!file || !project) return; setBusy(true); try { const form = new FormData(); form.set('file',file); form.set('projectId',project.id); const result = await apiFetch<Attachment>('/api/files', { method: 'POST', body: form }); setFiles(old => [...old,result]); } catch (error) { toast((error as Error).message,true); } finally { setBusy(false); if (upload.current) upload.current.value = ''; } }} /></>}
    {tab === 'chats' && <><button className="button primary" onClick={() => { w.newChat(project!.id); onClose(); }}><Plus size={16} />프로젝트에서 새 대화</button>{chats.map(chat => <button className="search-result" key={chat.id} onClick={() => { void w.openConversation(chat.id); onClose(); }}><strong>{chat.title}</strong><small>{new Date(chat.updatedAt).toLocaleDateString()}</small></button>)}{chatMore && <button className="button" onClick={async () => { try { const result = await apiFetch<{ items: Conversation[]; hasMore: boolean }>(`/api/conversations?projectId=${project!.id}&offset=${chats.length}`); setChats(old => [...old,...result.items]); setChatMore(result.hasMore); } catch (error) { toast((error as Error).message, true); } }}>더 보기</button>}</>}
  </div></Dialog>;
}
